# Generated by Django 3.1.6 on 2021-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Contact', models.CharField(max_length=50, null=True)),
                ('Iname', models.CharField(max_length=50, null=True)),
                ('Size', models.CharField(max_length=50, null=True)),
                ('Type', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
