# Generated by Django 3.1.6 on 2021-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0002_auto_20210425_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Iname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
