# Generated by Django 3.1.6 on 2021-04-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EWS', '0005_auto_20210428_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='clientss',
            new_name='clients',
        ),
    ]
